name       : cdrtools
version    : 3.02
release    : 3
source     :
    - http://downloads.sourceforge.net/cdrtools/cdrtools-3.02a06.tar.bz2 : ed79ab99414352ea9305163660b52b6a82394466bae03aebdbe2150997835eb1
license    : CDDL-1.0
component  : library
summary    : CD Recording Utilities
description: |
    CD Recording Utilities
build      : |
    %make LINKMODE=dynamic -j1
install    : |
    %make_install INS_BASE=/usr LINKMODE=dynamic -j1
    mv $installdir/usr/lib $installdir/%libdir%
    rm -rf $installdir/%libdir%/profiled
    rm  $installdir/%libdir%/*.a
    # Conflicts with dvdrw tools
    rm $installdir/usr/bin/btcflash
