name       : cdrtools
version    : '3.02_9'
release    : 4
source     :
    - https://10gbps-io.dl.sourceforge.net/project/cdrtools/alpha/cdrtools-3.02a09.tar.bz2 : aa28438f458ef3f314b79f2029db27679dae1d5ffe1569b6de57742511915e81
license    : CDDL-1.0
component  : library
summary    : CD Recording Utilities
description: |
    CD Recording Utilities
build      : |
    %make LINKMODE=dynamic -j1
install    : |
    %make_install INS_BASE=/usr LINKMODE=dynamic -j1
    mv $installdir/usr/lib $installdir/%libdir%
    rm -rf $installdir/%libdir%/profiled
    rm  $installdir/%libdir%/*.a
    # Conflicts with dvdrw tools
    rm $installdir/usr/bin/btcflash
