name       : cdrtools
version    : '3.02_9'
release    : 5
source     :
    - https://jztkft.dl.sourceforge.net/project/cdrtools/alpha/cdrtools-3.02a09.tar.gz : c7e4f732fb299e9b5d836629dadf5512aa5e6a5624ff438ceb1d056f4dcb07c2
license    : CDDL-1.0
component  : library
summary    : CD Recording Utilities
description: |
    CD Recording Utilities
build      : |
    %make LINKMODE=dynamic -j1
install    : |
    %make_install INS_BASE=/usr LINKMODE=dynamic -j1
    mv $installdir/usr/lib $installdir/%libdir%
    rm -rf $installdir/%libdir%/profiled
    rm  $installdir/%libdir%/*.a
    # Conflicts with dvdrw tools
    rm $installdir/usr/bin/btcflash
    rm -r $installdir/usr/share/doc